language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - sudo python2 -m pip install ipykernel "ipython<6"
  - python2 -m ipykernel install --user
  - python -m pip install ipykernel "ipython<6"
  - python -m ipykernel install --user
  - pip install -e .
  - pip install pytest
# command to run tests
script: py.test
